name: 'finance_analytics'
version: '1.0.0'
config-version: 2

profile: 'finance_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance_analytics:
    staging:
      +schema: STAGING
    core:
      +schema: CORE
    intermediate:
      +schema: CORE
    marts:
      +schema: MARTS